LABORATORIO 1

1. VECTORES Y MATRICES

1.1
```{r}

student_1 <- c(50.4,62.3,92.1,77.6,TRUE)
student_2 <- c(41.7,87.9,75.3,72.4,TRUE)
student_3 <- c(30.3,67.8,69.3,71.2,TRUE)
student_4 <- c(65.4,85.1,92.3,96.8,TRUE)
student_5 <- c(70.4,88.2,95.2,90.7,TRUE)

```

1.2
```{r}
students_vector <- c(student_1,student_2,student_3,student_4,student_5)

students_vector
```

1.3
```{r}
students_matrix <- matrix(students_vector, byrow = TRUE, nrow = 5)

students_matrix
```

2. NOMBRADO DE UNA MATRIZ

2.1

```{r}
name_students <- c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones",
"Tom Hill")
name_students

name_courses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics",
"Legal_age")
name_courses_legal_age

```

2.2

```{r}
colnames(students_matrix)<-name_courses_legal_age
rownames(students_matrix) <- name_students
students_matrix
```

3. rowSums, cbind

3.1
```{r}

total_grade_student <- rowSums(students_matrix[,c(1, 2, 3, 4)])

```
3.2

```{r}
result_students <- cbind(students_matrix, total_grade_student)
result_students
```

4. SELECCIONANDO ELEMENTOS DE UNA MATRIZ

4.1
```{r}

selected_elements <- result_students[c(1,3,5),c(2,4)]
selected_elements
```

5. DATA FRAMES

5.1

```{r}

students_grades_df <- data.frame(result_students)

students_grades_df

```
5.2

```{r}
subset(students_grades_df,subset = Accounting > 80 & Legal_age == TRUE)

```

6.Funciones, Condicionales y Bucles

6.1 y 6.2

```{r}
students_projection <- function(result_students) {
  new_result_students <- result_students[,1:4]
  for(i in 1:nrow(new_result_students)){
    for(j in 1:ncol(new_result_students)){
      if(new_result_students[i,j] <= 45){
        print("Student at risk")
      } else if(new_result_students[i,j] > 45 & new_result_students[i,j] < 61){
        print("“Student may be approved")
      } else if(new_result_students[i,j] >= 61){
        print("Student approved")
      }
      print(paste("Nota:",new_result_students[i,j]))
    }
  }
}

students_projection(result_students)

```
7. Data frames y lapply

7.1
```{r}

index_education <- function(grande) {
  return (1+(grande/100))/2
}
index_education(100)

```

7.2

```{r}
students_grades_df[,1:4]
all_students_grade <- students_grades_df[,1:4]
all_students_grade
```

7.3

```{r}

lapply(all_students_grade, index_education)

```

8. Math utilities

8.1
```{r}

score_mean <- vapply(students_grades_df[,1:4],mean,numeric(1))
score_mean

```

